### ISSUE TITLE
If you list more than one acronym in a comment, its not clear whether the add works

### ISSUE THREAD

**Issue by tankorsmash** [brunosardinepi/metalcoreacronymbot#1]
https://www.reddit.com/r/Metalcore/comments/t5vx07/i_never_understand_what_band_you_mean_when_you/hz8rowf/?context=2

![image](https://user-images.githubusercontent.com/1312390/156665751-e67add0a-cb79-4112-bdc1-9e8e9be38ee2.png)

Possible solutions include: 'ive added the acronym XYZ' in the message to show that it doesn't work, or add a `list` command to split out the results.

**Comment by brunosardinepi** [comment]
Thanks for this! I haven't looked at it since I initially wrote it, so I'll add this feature in soon. 

I also noticed that the acronyms in the screenshot aren't all uppercase, so I wonder how it's handling that. I'll look into that too.

**Comment by tankorsmash** [comment]
Thanks! I assumed it uppercased the acronyms by default, so I was definitely being lazy there!

**Comment by brunosardinepi** [comment]
It very well may be, but I wrote it in about 30 minutes while on my lunch break so I assume I cut some corners. Feel free to submit a pull request and if not, I'll check it out tonight.

**Comment by tankorsmash** [comment]
Thank you! It's been helpful for something that you put together that fast

**Comment by brunosardinepi** [comment]
Ok so instead of adding a bunch of logic where I have to check each acronym for validity, see if we already have it in the database, and then report back the results for every use case, I just limited it to one band per add/delete request and updated the bot information footer. I also checked that it will convert add/delete requests to uppercase. Finally, I added a check to see if a band already exists before adding it to prevent duplicates. Hope that satisfies your request for now and thanks again for reaching out.
